version: '3'

services:
  app:
    container_name: xed_web
    build: .

    environment:
      # To reload app on windows
      WATCHPACK_POLLING: true
      CHOKIDAR_USEPOLLING: true

    env_file: .env
    restart: always

    volumes:
      - ./app/public:/app/public
      - ./app/src:/app/src
      # - /app/node_modules

    ports:
      - 3000:3000
